version: "3.7"

services:
  ui:
    #    image: "node:12"
    image: estuaryoss/ui:latest
    #    working_dir: /home/node/app #already set
    environment:
      - NODE_ENV=development #production
      - SERVICE_BACKEND_URL=http://localhost:4000 #the machine where the backend is deployed
      - SERVICE_USERNAME=insertHereUsernameRef
      - SERVICE_PASSWORD=insertHerePasswordRef
    #    volumes:
    #      - ./:/home/node/app
    expose:
      - "8080"
    ports:
      - "8080:8080"
