version: "3.7"

services:
  ui:
    #    image: "node:12"
    image: estuaryoss/ui:latest
    #    working_dir: /home/node/app #already set
    environment:
      - NODE_ENV=development #production
      - SERVICE_BACKEND_URL=http://localhost:8080 #the machine where the Discovery backend is deployed
      - SERVICE_USERNAME=admin
      - SERVICE_PASSWORD=estuaryoss123! #change it !!!
    #    volumes:
    #      - ./:/home/node/app
    expose:
      - "8080"
    ports:
      - "8080:8080"
